use_default_settings: true

general:
  debug: false
  instance_name: "Searchtastic SearXNG"

search:
  safe_search: 0
  formats:
    - html
    - json
    - csv
    - rss

categories_as_tabs:
  general:
  images:
  videos:
  news:
  map:
  music:
  it:
  science:
  files:
  social media:

server:
  secret_key: "change-me-with-SEARXNG_SECRET"
  limiter: false
  image_proxy: true

plugins:
  searx.plugins.calculator.SXNGPlugin:
    active: true
  searx.plugins.hash_plugin.SXNGPlugin:
    active: true
  searx.plugins.self_info.SXNGPlugin:
    active: true
  searx.plugins.tracker_url_remover.SXNGPlugin:
    active: true
  searx.plugins.unit_converter.SXNGPlugin:
    active: true
  searx.plugins.ahmia_filter.SXNGPlugin:
    active: true
  searx.plugins.hostnames.SXNGPlugin:
    active: false
  searx.plugins.oa_doi_rewrite.SXNGPlugin:
    active: true
  searx.plugins.tor_check.SXNGPlugin:
    active: false

engines:
  - name: google
    disabled: false
  - name: bing
    disabled: false
  - name: duckduckgo
    disabled: false
  - name: brave
    disabled: false
  - name: startpage
    disabled: false
  - name: yahoo
    disabled: false
  - name: qwant
    disabled: false
  - name: mojeek
    disabled: false
  - name: marginalia
    disabled: false
  - name: wiby
    disabled: false
  - name: yep
    disabled: false
  - name: presearch
    disabled: false
  - name: github
    disabled: false
  - name: stackoverflow
    disabled: false
  - name: askubuntu
    disabled: false
  - name: superuser
    disabled: false
  - name: mdn
    disabled: false
  - name: hackernews
    disabled: false
  - name: docker hub
    disabled: false
  - name: pypi
    disabled: false
  - name: npm
    disabled: false
  - name: wikipedia
    disabled: false
  - name: wikibooks
    disabled: false
  - name: wiktionary
    disabled: false
  - name: arxiv
    disabled: false
  - name: semantic scholar
    disabled: false
  - name: google scholar
    disabled: false
  - name: pubmed
    disabled: false
  - name: openalex
    disabled: false
  - name: crossref
    disabled: false
  - name: reddit
    disabled: false
